name: Test Database Tool
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: ${{secrets.DB_NAME}}
          POSTGRES_USER: ${{secrets.DB_USER}}
          POSTGRES_PASSWORD: ${{secrets.DB_PASSWORD}}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create Stored Procedures
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: |
          export PGPASSWORD=$DB_PASSWORD
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -a -f ./src/evagram/database/sql/proc_create_owners.sql
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -a -f ./src/evagram/database/sql/proc_create_experiments.sql
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -a -f ./src/evagram/database/sql/proc_create_groups.sql
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -a -f ./src/evagram/database/sql/proc_create_plots.sql
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -a -f ./src/evagram/database/sql/proc_create_variables.sql
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -a -f ./src/evagram/database/sql/proc_create_observations.sql
          psql -h $DB_HOST -U $DB_USER -d $DB_NAME -a -f ./src/evagram/database/sql/proc_create_observation_variable.sql

      - name: Run Input Tool
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python ./src/evagram/database/input_tool.py ./tests/eva

      - name: Run Test Script
        env:
          DB_HOST: ${{secrets.DB_HOST}}
          DB_PORT: ${{secrets.DB_PORT}}
          DB_NAME: ${{secrets.DB_NAME}}
          DB_USER: ${{secrets.DB_USER}}
          DB_PASSWORD: ${{secrets.DB_PASSWORD}}
        run: python ./tests/test_input_tool.py
